version: "3.9"
name: polls

networks:
    polls:

services:

    nginx:
        image: nginx:stable
        volumes: 
            - ./html:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
        networks:
            - polls

    php:
        build: 
            context: .
            dockerfile: ./Dockerfile-php
        volumes: 
            - ./html:/var/www/html
        ports:
            - 9000:9000
        restart: always
        networks:
            - polls

    db:
        image: mysql:latest
        volumes: 
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            - MYSQL_DATABASE=polls
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - polls
